name: Makefile CI

on:
  push:
    branches: [ "android12-stable" ]
  pull_request:
    branches: [ "android12-stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python python3 flex cpio libncurses5-dev wget
      
    - name: Install dependencies
      run: git clone https://github.com/UtsavBalar1231/Drone-scripts.git --depth=1 -b test script && cd script
      
    - name: Run check
      run: ./setup-drone --aosp-clang
      
    - name: Run distcheck
      run: ./build-kernel --aosp-clang
